### ISSUE TITLE
Git LFS fails - too large for repo bandwidth settings

### ISSUE THREAD

**Issue by guitarman513** [THU-EarthInformationScienceLab/Satellite-Instrument-NER#1]
Hello,
Thank you for publishing your model on huggingface. I would like to download the dataset in this repo, but when I run `git lfs pull` I get this error:

batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.
error: failed to fetch some objects from 'https://github.com/THU-EarthInformationScienceLab/Satellite-Instrument-NER.git/info/lfs'

I believe it is because the lfs settings for this repo are not sufficient. 

Are you willing/able to share your data files in another way, so I may expand upon them with other data that I have been gathering?

Thank you,
Joe

**Comment by lmforestbird** [comment]
Hi Joe,
Thank you for your attention. 
You can try this shared link: https://cloud.tsinghua.edu.cn/d/1792617d3ccd4cc8b1e7/
